import React from 'react';
import './About.css';
import Banner from '../Banner/Banner';
import Footer from '../Footer/Footer';

const About = () => {
    return (
        <div>
             <Banner/>
             <h1>Our philosophy</h1>
            
            <div className="about-body">
             <h3>User friendly</h3>
             <p>The information is very difficult to retrieve and to find particular information like- E.g. -
To find out about the patient’s history, the user has to go through various registers. This
results in in convenienceand wastage of time.
.</p>
             <hr></hr>
             <h3>Simple fast</h3>
             <p>The information generated by various transactions takes time and efforts to be stored at
right place.</p>
             <hr />

             <h3>Lack of prompt updating:</h3>
             <p>Various changes to information like patient details or immunization details of child are
difficult to make as paper work is involved</p>

             <hr />

<h3>Error prone manual calculation</h3>
<p>Manual calculations are error prone and take a lot of time this may result in incorrect
information. For example calculation of patient’s bill based on various treatments.</p>

            </div>
            <Footer/>
        </div>
        
    );
};

export default About;